// Generated by CoffeeScript 1.8.0
(function() {
  var Hello, b;

  b = ReactBootstrap;

  Hello = React.createClass({
    getInitialState: function() {
      return {
        input1: 0,
        input2: 0
      };
    },
    render: function() {
      var name1, sieze1, total;
      total = this.state.input1 + this.state.input2;
      name1 = "input1";
      sieze1 = 1;
      return React.createElement("div", {
        "style": {
          maxWidth: 800,
          minWidth: 800,
          width: 800,
          "border-width": 1,
          "border-style": "solid",
          background: "#FFF"
        }
      }, React.createElement(b.Table, {
        "striped": true,
        "bordered": true,
        "condensed": true,
        "hover": true,
        "style": {
          width: "100%"
        }
      }, React.createElement("thead", null, React.createElement("tr", null, React.createElement("th", {
        "style": {
          width: 40
        }
      }, "#"), React.createElement("th", {
        "style": {
          width: 180
        }
      }, "First Name"), React.createElement("th", {
        "style": {
          width: 180
        }
      }, "Last Name"), React.createElement("th", {
        "style": {
          width: 100
        }
      }, "Username"))), React.createElement("tbody", null, React.createElement("tr", null, React.createElement("td", null, "1"), React.createElement("td", null, "Mark"), React.createElement("td", null, "Otto"), React.createElement("td", null, "@mdo")), React.createElement("tr", null, React.createElement("td", null, "2"), React.createElement("td", null, "Jacob"), React.createElement("td", null, "Thornton"), React.createElement("td", null, "@fat")), React.createElement("tr", null, React.createElement("td", null, "3"), React.createElement("td", {
        "colSpan": "2"
      }, "Larry the Bird"), React.createElement("td", null, "@twitter")))), React.createElement(b.Table, {
        "condensed": true,
        "style": {
          width: "100%"
        }
      }, React.createElement("tbody", null, React.createElement("tr", null, React.createElement("td", {
        "align": "right",
        "valign": "middle",
        "style": {
          width: 100,
          "text-align": "right",
          "vertical-align": "middle"
        }
      }, "TEST"), React.createElement("td", null, React.createElement("div", null, React.createElement(b.Input, {
        "type": "text",
        "value": this.state[name1],
        "style": {
          padding: 1
        },
        "name": name1,
        "onChange": this.handleChange
      }))), React.createElement("td", {
        "style": {
          width: 100
        }
      }, "Otto")))), total, React.createElement("br", null), React.createElement(b.Row, null, React.createElement(b.Col, {
        "xs": sieze1
      }, React.createElement(b.Input, {
        "type": "text",
        "value": this.state[name1],
        "style": {
          padding: 1
        },
        "name": name1,
        "onChange": this.handleChange
      }))), React.createElement(b.Row, null, React.createElement(b.Col, {
        "xs": 1.
      }, "\u00a0TEST"), React.createElement(b.Col, {
        "xs": 2.
      }, React.createElement(b.Input, {
        "type": "select",
        "label": ''
      }, React.createElement("option", {
        "value": ""
      }), React.createElement("option", {
        "value": "V1"
      }, "Value 1"), React.createElement("option", {
        "value": "V2"
      }, "Value 2")))));
    },
    handleChange: function(e) {
      var change;
      change = {};
      change[e.target.name] = Number(e.target.value);
      return this.setState(change);
    }
  });

  window.onload = function() {
    return React.render(React.createElement(Hello, null), document.getElementById('example'));
  };

}).call(this);
